name: PR Build and Test

on:
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  # This ensures we can compare changes with the previous commit
                  fetch-depth: 2
                  # We want to compare on the PR request not master
                  ref: ${{ github.event.pull_request.head.sha }}

            - uses: actions/setup-node@v1
              with:
                  node-version: "14"
                  registry-url: "https://registry.npmjs.org"

            - name: Setup timezone
              uses: zcong1993/setup-timezone@master
              with:
                  timezone: America/Los_Angeles

            - run: yarn --fixed-lockfile
            - run: yarn run test:unit
            # - run: yarn run workspace:test:sdk-v2
            # - run: yarn run workspace:dev:web2
            # - run: yarn run workspace:test:web2
